zerossl_eab_key_id: !vault |
          $ANSIBLE_VAULT;1.2;AES256;rhelbu_vault
          [PLACEHOLDER - replace with encrypted ZeroSSL EAB Key ID]
zerossl_hmac_key: !vault |
          $ANSIBLE_VAULT;1.2;AES256;rhelbu_vault
          [PLACEHOLDER - replace with encrypted ZeroSSL HMAC Key]
